version: "3"

services:
  #####################################
  #    Setup node server
  #####################################
  server:
    build: ./server
    expose:
      - ${APP_SERVER_PORT}
    enviroment:
      API_HOST: ${API_HOST}
      APP_SERVER_PORT: ${APP_SERVER_PORT}
    env_file:
    - .env
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    volumes:
      - ./server/src:/src/app/fr-chatapp-server/src
    command: npm run dev

  #####################################
  #    Setup node client
  #####################################
  client:
    build: ./app
    enviroment:
      - REACT_APP_PORT=${REACT_APP_PORT}
    env_file:
    - .env
    expose:
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ./app/src:/src/app/fr-chatapp-client/src
      - ./app/public:/src/app/fr-chatapp-client/public
    links:
      - server
    command: npm run start
