version: "3"

services:
  #####################################
  #    Setup node server
  #####################################
  server:
    build: ./server
    expose:
      - ${APP_SERVER_PORT}
    environment:
      API_HOST: ${API_HOST}
      APP_SERVER_PORT: ${APP_SERVER_PORT}
    env_file:
      - .env
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    volumes:
      - ./server/src:/srv/app/fr-chatapp-server/src
    links:
      - mongo
    depends_on:
      - mongo
    command: node index.js

  #####################################
  #    Setup node client
  #####################################
  client:
    build: ./app
    environment:
      - REACT_APP_PORT=${REACT_APP_PORT}
    env_file:
      - .env
    expose:
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ./app/src:/srv/app/fr-chatapp-client/src
      - ./app/public:/srv/app/fr-chatapp-client/public
    links:
      - server
    command: npm run start
  #####################################
  #    Setup node database
  #####################################
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
